#!/usr/bin/env python
import math
import rospy
import wheel_encoder_interface

from svea_arduino.msg import lli_encoder
from geometry_msgs.msg import TwistWithCovarianceStamped
from nav_msgs.msg import Odometry

def main():
    encoder_interface = wheel_encoder_interface.WheelEncoderInterface()
    encoder_interface.start(block=True)

if __name__ == '__main__':
    
    rospy.init_node('wheel_encoder_interface', anonymous=True)
    rospy.loginfo("Successful initilization of node")

    main()
